/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @format
 */

const tutorials = () => {
  const allTutorialMetadata = require('./tutorials.json');
  const tutorialsSidebar = [{
    type: 'category',
    label: 'Tutorials',
    collapsed: false,
    items: [
      {
        type: 'doc',
        id: 'tutorials-old/index',
        label: 'Overview',
      },
    ],
  },];
  for (var category in allTutorialMetadata) {
    const categoryItems = allTutorialMetadata[category];
    const items = [];
    categoryItems.map(item => {
      items.push({
        type: 'doc',
        label: item.title,
        id: `tutorials-old/${item.id}/index`,
      });
    });

    tutorialsSidebar.push({
      type: 'category',
      label: category,
      items: items,
    });
  }
  return tutorialsSidebar;
};

export default {
  docs_old: {
    "Introduction": ["docs-old/why-ax"],
    "Getting Started": ["docs-old/installation", "docs-old/api", "docs-old/glossary"],
    "Algorithms": ["docs-old/bayesopt", "docs-old/banditopt"],
    "Components": ["docs-old/core", "docs-old/trial-evaluation", "docs-old/data", "docs-old/models", "docs-old/storage"],
  },
  docs: [{
    type: 'autogenerated',
    dirName: 'docs'
  }],
  tutorials_old: tutorials(),
  tutorials: [{
    type: 'autogenerated',
    dirName: 'tutorials'
  }],
  recipes: [{
    type: 'autogenerated',
    dirName: 'recipes'
  }],
};
