# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Deploy

on:
  # TODO: Temporarily allow running manually while making changes on fork. Disable before merging back into facebook/Ax
  workflow_dispatch:
  release:
    types: [created]

jobs:
  # TODO: Temporarily disabled while making changes on fork. Re-enable before merging back into facebook/Ax
  # tests-and-coverage-latest:
  #   name: Tests with latest BoTorch
  #   uses: ./.github/workflows/reusable_test.yml
  #   with:
  #     pinned_botorch: false
  #   secrets: inherit

  # tests-and-coverage-pinned:
  #   name: Tests with pinned BoTorch
  #   uses: ./.github/workflows/reusable_test.yml
  #   with:
  #     pinned_botorch: true
  #   secrets: inherit

  create-docusaurus-version:
    # needs: tests-and-coverage-pinned # only run if test step succeeds
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create new version in Docusaurus
      run: |
        python3 scripts/convert_ipynb_to_mdx.py
        cd website
        yarn
        yarn docusaurus docs:version ${{ github.event.release.tag_name }}
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add --all
        git commit -m "Publish version ${{ github.event.release.tag_name }} of site"
        # TODO: Temporarily changed while making changes on fork. Revert before merging back into facebook/Ax
        git push --force https://github.com/CristianLara/Ax.git HEAD:main

  publish-website:
    needs: create-docusaurus-version
    name: Publish website
    uses: ./.github/workflows/website.yml
    secrets: inherit

  # TODO: Temporarily disabled while making changes on fork. Re-enable before merging back into facebook/Ax
  # deploy:

  #   needs: tests-and-coverage-pinned # only run if test step succeeds
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Set up Python
  #     uses: actions/setup-python@v5
  #     with:
  #       python-version: "3.10"
  #   - name: Install dependencies
  #     run: |
  #       # use stable Botorch
  #       pip install -e ".[dev,mysql,notebook]"
  #       pip install wheel
  #   - name: Fetch all history for all tags and branches
  #     run: git fetch --prune --unshallow
  #   - name: Build wheel
  #     run: |
  #       python setup.py sdist bdist_wheel
  #   - name: Deploy to PyPI
  #     uses: pypa/gh-action-pypi-publish@release/v1
  #     with:
  #       user: __token__
  #       password: ${{ secrets.PYPI_TOKEN }}
  #       verbose: true
