name: Test Docusaurus

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  make-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make test commit
      run: |
        git rev-parse HEAD
        git log | head -n 5
        echo "testing" >> README.md
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add --all
        git commit -m "test change to README.md"
        git push --force origin HEAD:$GITHUB_HEAD_REF
        git rev-parse HEAD
        git log | head -n 5
        echo "GH_COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

  checkout-latest-commit:
    needs: make-commit
    name: Checkout latest commit
    uses: ./.github/workflows/test-checkout-specific-commit.yml.yml
    with:
      ref: ${{ env.GH_COMMIT_SHA }}
    secrets: inherit
