name: Publish Website

on:
  workflow_dispatch:
  push:
    branches: [ cris-testing-merge-release-branch ]


jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'cris-testing-merge-release-branch'
        fetch-depth: 0
    - name: Sync release branch with main
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git merge origin/main
