name: Test Docusaurus

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  create-docusaurus-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create new version in Docusaurus
      run: |
        echo "testing" >> README.md
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add --all
        git commit -m "test change to README.md"
        # TODO: Temporarily changed while making changes on fork. Revert before merging back into facebook/Ax
        git push
