name: Publish Website

on:
  workflow_dispatch:
  push:
    branches: [ main ]


jobs:

  publish-stable-website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      env:
        ALLOW_BOTORCH_LATEST: true
        ALLOW_LATEST_GPYTORCH_LINOP: true
      run: |
        # use latest BoTorch
        pip install git+https://github.com/cornellius-gp/gpytorch.git
        pip install git+https://github.com/pytorch/botorch.git
        pip install -e ".[tutorial]"
    - name: Publish latest website
      run: |
        bash scripts/publish_site.sh
