name: Publish Website

on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
  workflow_dispatch:
  push:
    branches: [ main ]


jobs:

  publish-stable-website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
          ref: ${{ inputs.ref || github.ref }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      env:
        ALLOW_BOTORCH_LATEST: true
        ALLOW_LATEST_GPYTORCH_LINOP: true
      run: |
        # use latest BoTorch
        pip install git+https://github.com/cornellius-gp/gpytorch.git
        pip install git+https://github.com/pytorch/botorch.git
        pip install -e ".[tutorial]"
    - name: Publish latest website
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        bash scripts/make_docs.sh -b
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
          branch: gh-pages # The branch the action should deploy to.
          folder: website/build # The folder the action should deploy.
